project_02/config/routes.rb
Rails.application.routes.draw do
  resources :aprovacao_comentarios
  resources :comentarios
  resources :ators
  resources :filmes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "filmes#index"
end

project_02/app/models/aprovacao_comentario.rb
class AprovacaoComentario < ApplicationRecord
  belongs_to :comentario
end

project_02/app/controllers/aprovacao_comentarios_controller.rb
class AprovacaoComentariosController < ApplicationController
  before_action :set_aprovacao_comentario, only: %i[ show edit update destroy ]

  # GET /aprovacao_comentarios or /aprovacao_comentarios.json
  def index
    @aprovacao_comentarios = AprovacaoComentario.all
  end

  # GET /aprovacao_comentarios/1 or /aprovacao_comentarios/1.json
  def show
  end

  # GET /aprovacao_comentarios/new
  def new
    @aprovacao_comentario = AprovacaoComentario.new
  end

  # GET /aprovacao_comentarios/1/edit
  def edit
  end

  # POST /aprovacao_comentarios or /aprovacao_comentarios.json
  def create
    @aprovacao_comentario = AprovacaoComentario.new(aprovacao_comentario_params)

    respond_to do |format|
      if @aprovacao_comentario.save
        format.html { redirect_to aprovacao_comentario_url(@aprovacao_comentario), notice: "Aprovacao comentario was successfully created." }
        format.json { render :show, status: :created, location: @aprovacao_comentario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @aprovacao_comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /aprovacao_comentarios/1 or /aprovacao_comentarios/1.json
  def update
    respond_to do |format|
      if @aprovacao_comentario.update(aprovacao_comentario_params)
        format.html { redirect_to aprovacao_comentario_url(@aprovacao_comentario), notice: "Aprovacao comentario was successfully updated." }
        format.json { render :show, status: :ok, location: @aprovacao_comentario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @aprovacao_comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /aprovacao_comentarios/1 or /aprovacao_comentarios/1.json
  def destroy
    @aprovacao_comentario.destroy

    respond_to do |format|
      format.html { redirect_to aprovacao_comentarios_url, notice: "Aprovacao comentario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_aprovacao_comentario
      @aprovacao_comentario = AprovacaoComentario.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def aprovacao_comentario_params
      params.require(:aprovacao_comentario).permit(:comentario_id, :data_aprovacao)
    end
end

project_02/app/helpers/aprovacao_comentarios_helper.rb
module AprovacaoComentariosHelper
end

project_02/app/views/aprovacao_comentarios/_aprovacao_comentario.html.erb
<div id="<%= dom_id aprovacao_comentario %>">
  <p>
    <strong>Comentario:</strong>
    <%= aprovacao_comentario.comentario_id %>
  </p>

  <p>
    <strong>Data aprovacao:</strong>
    <%= aprovacao_comentario.data_aprovacao %>
  </p>

</div>

project_02/app/views/aprovacao_comentarios/_form.html.erb
<%= form_with(model: aprovacao_comentario) do |form| %>
  <% if aprovacao_comentario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(aprovacao_comentario.errors.count, "error") %> prohibited this aprovacao_comentario from being saved:</h2>

      <ul>
        <% aprovacao_comentario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :comentario_id, style: "display: block" %>
    <%= form.text_field :comentario_id %>
  </div>

  <div>
    <%= form.label :data_aprovacao, style: "display: block" %>
    <%= form.date_field :data_aprovacao %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

project_02/app/views/aprovacao_comentarios/edit.html.erb
<h1>Editing aprovacao comentario</h1>

<%= render "form", aprovacao_comentario: @aprovacao_comentario %>

<br>

<div>
  <%= link_to "Show this aprovacao comentario", @aprovacao_comentario %> |
  <%= link_to "Back to aprovacao comentarios", aprovacao_comentarios_path %>
</div>

project_02/app/views/aprovacao_comentarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Aprovacao comentarios</h1>

<div id="aprovacao_comentarios">
  <% @aprovacao_comentarios.each do |aprovacao_comentario| %>
    <%= render aprovacao_comentario %>
    <p>
      <%= link_to "Show this aprovacao comentario", aprovacao_comentario %>
    </p>
  <% end %>
</div>

<%= link_to "New aprovacao comentario", new_aprovacao_comentario_path %>

project_02/app/views/aprovacao_comentarios/new.html.erb
<h1>New aprovacao comentario</h1>

<%= render "form", aprovacao_comentario: @aprovacao_comentario %>

<br>

<div>
  <%= link_to "Back to aprovacao comentarios", aprovacao_comentarios_path %>
</div>

project_02/app/views/aprovacao_comentarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @aprovacao_comentario %>

<div>
  <%= link_to "Edit this aprovacao comentario", edit_aprovacao_comentario_path(@aprovacao_comentario) %> |
  <%= link_to "Back to aprovacao comentarios", aprovacao_comentarios_path %>

  <%= button_to "Destroy this aprovacao comentario", @aprovacao_comentario, method: :delete %>
</div>