project_02/config/routes.rb
Rails.application.routes.draw do
  resources :aprovacao_comentarios
  resources :comentarios
  resources :ators
  resources :filmes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "filmes#index"
end

project_02/app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :Filme

  default_scope {where(approved:false)}

 validates :filme, :comentario, presence: true
end

project_02/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: %i[ show edit update destroy ]
  before_action :set_all_filmes, only: %i[new edit create update]

  # GET /comentarios or /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1 or /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios or /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to comentario_url(@comentario), notice: "Comentario was successfully created." }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1 or /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to comentario_url(@comentario), notice: "Comentario was successfully updated." }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1 or /comentarios/1.json
  def destroy
    @comentario.destroy

    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: "Comentario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    def set_all_filmes
      @all_filmes = Filme.all.pluck(:titulo, :id)
    end

    # Only allow a list of trusted parameters through.
    def comentario_params
      params.require(:comentario).permit(:comentario, :Filme_id)
    end
  end

project_02/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

project_02/app/views/comentarios/_comentario.html.erb
<div id="<%= dom_id comentario %>">
  <p>
    <strong>Comentario:</strong>
    <%= comentario.comentario %>
  </p>

  <p>
    <strong>Filme:</strong>
    <%= comentario.Filme_id %>
  </p>

</div>

project_02/app/views/comentarios/_form.html.erb
<%= form_with(model: comentario) do |form| %>
  <% if comentario.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
        <% comentario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :comentario, style: "display: block" %>
    <%= form.text_area :comentario %>
  </div>

  <div>
    <%= form.label :Filme_id, style: "display: block" %>
    <%= form.text_field :Filme_id, @all_filmes, {}, {} %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

project_02/app/views/comentarios/edit.html.erb
<h1>Editing comentario</h1>

<%= render "form", comentario: @comentario %>

<br>

<div>
  <%= link_to "Show this comentario", @comentario %> |
  <%= link_to "Back to comentarios", comentarios_path %>
</div>

project_02/app/views/comentarios/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comentarios</h1>

<div id="comentarios">
  <% @comentarios.each do |comentario| %>
    <%= render comentario %>
    <p>
      <%= link_to "Show this comentario", comentario %>
    </p>
  <% end %>
</div>

<%= link_to "New comentario", new_comentario_path %>

project_02/app/views/comentarios/new.html.erb
<h1>New comentario</h1>

<%= render "form", comentario: @comentario %>

<br>

<div>
  <%= link_to "Back to comentarios", comentarios_path %>
</div>

project_02/app/views/comentarios/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comentario %>

<div>
  <%= link_to "Edit this comentario", edit_comentario_path(@comentario) %> |
  <%= link_to "Back to comentarios", comentarios_path %>

  <%= button_to "Destroy this comentario", @comentario, method: :delete %>
</div>