project_02/config/routes.rb
Rails.application.routes.draw do
  resources :aprovacao_comentarios
  resources :comentarios
  resources :ators
  resources :filmes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "filmes#index"
end

project_02/app/models/filme.rb
class Filme < ApplicationRecord
    validates :titulo, :ano_lancamento, :elenco_atores,    presence: true
    validates :titulo,  uniqueness: true

    has_and_belongs_to_many :all_ators
    has_many :comentario, dependent: :destroy
end

project_02/app/controllers/filmes_controller.rb
class FilmesController < ApplicationController
  before_action :set_filme, only: %i[ show edit update destroy ]
  before_action :set_all_ators, only: %i[new edit create update]

  # GET /filmes or /filmes.json
  def index
    @filmes = Filme.all
  end

  # GET /filmes/1 or /filmes/1.json
  def show
  end

  # GET /filmes/new
  def new
    @filme = Filme.new
  end

  # GET /filmes/1/edit
  def edit
  end

  # POST /filmes or /filmes.json
  def create
    @filme = Filme.new(filme_params)

    respond_to do |format|
      if @filme.save
        format.html { redirect_to filme_url(@filme), notice: "Filme was successfully created." }
        format.json { render :show, status: :created, location: @filme }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /filmes/1 or /filmes/1.json
  def update
    respond_to do |format|
      if @filme.update(filme_params)
        format.html { redirect_to filme_url(@filme), notice: "Filme was successfully updated." }
        format.json { render :show, status: :ok, location: @filme }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @filme.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /filmes/1 or /filmes/1.json
  def destroy
    @filme.destroy

    respond_to do |format|
      format.html { redirect_to filmes_url, notice: "Filme was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_filme
      @filme = Filme.find(params[:id])
    end

    def set_all_ators
      @all_ators = Ator.all
    end

    # Only allow a list of trusted parameters through.
    def filme_params
      params.require(:filme).permit(:titulo, :ano_lancamento, :alenco_atores, :comentarios)
    end
end

project_02/app/helpers/filmes_helper.rb
module FilmesHelper
end

project_02/app/views/filmes/_filme.html.erb
<div id="<%= dom_id filme %>">
  <p>
    <strong>Titulo:</strong>
    <%= filme.titulo %>
  </p>

  <p>
    <strong>Ano lancamento:</strong>
    <%= filme.ano_lancamento %>
  </p>

  <%if show_alenco_atores%>
  <p>
    <strong>Alenco atores:</strong>
    <%= filme.alenco_atores %>
    <ul>
    <% filme.ators.each do |ator|%>
    <li>
    <%= ator.nome %>
    </li>
    <% end %>
    </ul>
  </p>
  <% end %>

  <p>
    <strong>Comentarios:</strong>
    <%= filme.comentarios %>
  </p>

</div>

project_02/app/views/filmes/_form.html.erb
<%= form_with(model: filme) do |form| %>
  <% if filme.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(filme.errors.count, "error") %> prohibited this filme from being saved:</h2>

      <ul>
        <% filme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :titulo, style: "display: block" %>
    <%= form.text_field :titulo %>
  </div>

  <div>
    <%= form.label :ano_lancamento, style: "display: block" %>
    <%= form.date_field :ano_lancamento %>
  </div>

  <div>
    <%= form.label :alenco_atores, style: "display: block" %>
    <%= form.text_field :alenco_atores %>
  </div>

  <div>
    <%= form.label :comentarios, style: "display: block" %>
    <%= form.text_area :comentarios %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

project_02/app/views/filmes/edit.html.erb
<h1>Editing filme</h1>

<%= render "form", filme: @filme %>

<br>

<div>
  <%= link_to "Show this filme", @filme %> |
  <%= link_to "Back to filmes", filmes_path %>
</div>

project_02/app/views/filmes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Filmes</h1>

<div id="filmes">
  <% @filmes.each do |filme| %>
    <%= render filme, show_alenco_atores: false %>
    <p>
      <%= link_to "Show this filme", filme %>
    </p>
  <% end %>
</div>

<%= link_to "New filme", new_filme_path %>

project_02/app/views/filmes/new.html.erb
<h1>New filme</h1>

<%= render "form", filme: @filme %>

<br>

<div>
  <%= link_to "Back to filmes", filmes_path %>
</div>

project_02/app/views/filmes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @filme, show_alenco_atores: true %>

<div>
  <%= link_to "Edit this filme", edit_filme_path(@filme) %> |
  <%= link_to "Back to filmes", filmes_path %>

  <%= button_to "Destroy this filme", @filme, method: :delete %>
</div>