project_02/config/routes.rb
Rails.application.routes.draw do
  resources :aprovacao_comentarios
  resources :comentarios
  resources :ators
  resources :filmes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "filmes#index"
end

project_02/app/models/ator.rb
class Ator < ApplicationRecord
  belongs_to :Ator

  has_many :filmes

  validates :nome, :ano_nascimento, :email, presence: true
  validates :email,  uniqueness: true
end

project_02/app/controllers/ators_controller.rb
class AtorsController < ApplicationController
  before_action :set_ator, only: %i[ show edit update destroy ]

  # GET /ators or /ators.json
  def index
    @ators = Ator.all
  end

  # GET /ators/1 or /ators/1.json
  def show
  end

  # GET /ators/new
  def new
    @ator = Ator.new
  end

  # GET /ators/1/edit
  def edit
  end

  # POST /ators or /ators.json
  def create
    @ator = Ator.new(ator_params)

    respond_to do |format|
      if @ator.save
        format.html { redirect_to ator_url(@ator), notice: "Ator was successfully created." }
        format.json { render :show, status: :created, location: @ator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ators/1 or /ators/1.json
  def update
    respond_to do |format|
      if @ator.update(ator_params)
        format.html { redirect_to ator_url(@ator), notice: "Ator was successfully updated." }
        format.json { render :show, status: :ok, location: @ator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ators/1 or /ators/1.json
  def destroy
    @ator.destroy

    respond_to do |format|
      format.html { redirect_to ators_url, notice: "Ator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ator
      @ator = Ator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def ator_params
      params.require(:ator).permit(:nome, :ano_nascimento, :email, :Ator_id)
    end
end

project_02/app/helpers/ators_helper.rb
module AtorsHelper
end

project_02/app/views/ators/_ator.html.erb
<div id="<%= dom_id ator %>">
  <p>
    <strong>Nome:</strong>
    <%= ator.nome %>
  </p>

  <p>
    <strong>Ano nascimento:</strong>
    <%= ator.ano_nascimento %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= ator.email %>
  </p>

  <p>
    <strong>Ator:</strong>
    <%= ator.Ator_id %>
  </p>

</div>

project_02/app/views/ators/_form.html.erb
<%= form_with(model: ator) do |form| %>
  <% if ator.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(ator.errors.count, "error") %> prohibited this ator from being saved:</h2>

      <ul>
        <% ator.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nome, style: "display: block" %>
    <%= form.text_field :nome %>
  </div>

  <div>
    <%= form.label :ano_nascimento, style: "display: block" %>
    <%= form.date_field :ano_nascimento %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :Ator_id, style: "display: block" %>
    <%= form.text_field :Ator_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

project_02/app/views/ators/edit.html.erb
<h1>Editing ator</h1>

<%= render "form", ator: @ator %>

<br>

<div>
  <%= link_to "Show this ator", @ator %> |
  <%= link_to "Back to ators", ators_path %>
</div>

project_02/app/views/ators/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ators</h1>

<div id="ators">
  <% @ators.each do |ator| %>
    <%= render ator %>
    <p>
      <%= link_to "Show this ator", ator %>
    </p>
  <% end %>
</div>

<%= link_to "New ator", new_ator_path %>

project_02/app/views/ators/new.html.erb
<h1>New ator</h1>

<%= render "form", ator: @ator %>

<br>

<div>
  <%= link_to "Back to ators", ators_path %>
</div>

project_02/app/views/ators/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @ator %>

<div>
  <%= link_to "Edit this ator", edit_ator_path(@ator) %> |
  <%= link_to "Back to ators", ators_path %>

  <%= button_to "Destroy this ator", @ator, method: :delete %>
</div>